apiVersion: 1

datasources:
  - name: DAH Agent Metrics
    uid: dah-agent-metrics
    type: prometheus
    access: proxy
    url: http://dah-agent-poc:8080/prometheus
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 5s
